apiVersion: v1
kind: ConfigMap
metadata:
  name: drift-detector-config
  namespace: monitoring
data:
  config.yaml: |
    models:
      - name: credit_risk_model
        baseline_dataset: s3://mlops-platform-datasets/credit_risk_baseline.csv
        prediction_topic: model-predictions.credit-risk
        features:
          - age
          - income
          - credit_score
          - employment_years
        metrics:
          - name: ks_test
            threshold: 0.2
          - name: psi
            threshold: 0.2
      - name: customer_churn_model
        baseline_dataset: s3://mlops-platform-datasets/customer_churn_baseline.csv
        prediction_topic: model-predictions.customer-churn
        features:
          - monthly_charges
          - total_charges
          - tenure
          - contract_type
        metrics:
          - name: ks_test
            threshold: 0.15
          - name: psi
            threshold: 0.15
    monitoring:
      check_interval_minutes: 60
      window_size_hours: 24
      min_samples: 1000
    storage:
      type: prometheus
      prometheus:
        push_gateway: http://prometheus.monitoring.svc.cluster.local:9091
        metric_prefix: model_drift
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drift-detector
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: drift-detector
  replicas: 1
  template:
    metadata:
      labels:
        app: drift-detector
    spec:
      containers:
        - name: drift-detector
          image: mlops-platform/drift-detector:latest
          imagePullPolicy: IfNotPresent
          args:
            - "--config=/etc/drift-detector/config.yaml"
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 512Mi
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-headless.kafka.svc.cluster.local:9092"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secret-key
          volumeMounts:
            - name: drift-detector-config
              mountPath: /etc/drift-detector
      volumes:
        - name: drift-detector-config
          configMap:
            name: drift-detector-config 