---
apiVersion: v1
kind: ConfigMap
metadata:
  name: batch-feature-engineering-config
  namespace: feature-engineering
data:
  POSTGRES_HOST: "postgresql.storage.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "mlops"
  FEATURE_STORE_URL: "http://feature-store.feature-engineering.svc.cluster.local"
  LOG_LEVEL: "INFO"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: batch-feature-engineering
  namespace: feature-engineering
spec:
  schedule: "0 2 * * *"  # Run daily at 2 AM
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: feature-engineering
            image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/mlops-platform/feature-engineering:latest
            imagePullPolicy: Always
            args:
            - "--feature-types=customer,product,customer_product"
            - "--lookback-days=30"
            resources:
              requests:
                cpu: "1000m"
                memory: "4Gi"
              limits:
                cpu: "2000m"
                memory: "8Gi"
            env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: batch-feature-engineering-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: batch-feature-engineering-config
                  key: POSTGRES_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: batch-feature-engineering-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: FEATURE_STORE_URL
              valueFrom:
                configMapKeyRef:
                  name: batch-feature-engineering-config
                  key: FEATURE_STORE_URL
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: batch-feature-engineering-config
                  key: LOG_LEVEL
          restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: batch-feature-engineering-manual
  namespace: feature-engineering
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
      - name: feature-engineering
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/mlops-platform/feature-engineering:latest
        imagePullPolicy: Always
        args:
        - "--feature-types=customer,product,customer_product"
        - "--lookback-days=30"
        resources:
          requests:
            cpu: "1000m"
            memory: "4Gi"
          limits:
            cpu: "2000m"
            memory: "8Gi"
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: batch-feature-engineering-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: batch-feature-engineering-config
              key: POSTGRES_PORT
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: batch-feature-engineering-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password
        - name: FEATURE_STORE_URL
          valueFrom:
            configMapKeyRef:
              name: batch-feature-engineering-config
              key: FEATURE_STORE_URL
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: batch-feature-engineering-config
              key: LOG_LEVEL
      restartPolicy: Never 