apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: postgres-connector
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-connect
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    tasks.max: 1
    connector.class: io.debezium.connector.postgresql.PostgresConnector
    
    # Connection information - set to use AWS RDS PostgreSQL
    database.hostname: ${POSTGRES_HOST}
    database.port: 5432
    database.user: postgres
    database.password: ${file:/opt/kafka/external-configuration/connector-config/postgres-credentials.properties:password}
    database.dbname: mlops
    database.server.name: postgres-server
    
    # Slot name for replication
    slot.name: debezium_slot
    
    # Only monitor essential tables to reduce resource consumption
    table.include.list: public.users,public.models,public.experiments
    
    # PostgreSQL specific configurations
    plugin.name: pgoutput
    publication.name: dbz_publication
    
    # Kafka topic naming schema
    topic.prefix: postgres-cdc
    
    # Default behavior on schema changes
    tombstones.on.delete: true
    
    # Basic transforms for simple use case
    transforms: unwrap
    transforms.unwrap.type: io.debezium.transforms.ExtractNewRecordState
    transforms.unwrap.drop.tombstones: false
    
    # Schema handling
    key.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: true
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: true
    
    # Reduced batch and queue sizes for lower resource usage
    max.batch.size: 1024
    max.queue.size: 4096
    poll.interval.ms: 2000
    heartbeat.interval.ms: 10000
    snapshot.mode: initial 