FROM ghcr.io/mlflow/mlflow:latest

# Install PostgreSQL client and required Python packages
RUN apt-get update && apt-get install -y postgresql-client libpq-dev gcc python3-dev && \
    pip install psycopg2 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Keep the entrypoint from the original image
ENTRYPOINT ["mlflow"] 