apiVersion: v1
kind: Namespace
metadata:
  name: storage
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: storage
data:
  redis.conf: |
    # Memory configuration for resource-constrained environment
    maxmemory 512mb
    maxmemory-policy volatile-lru
    
    # Persistence settings
    appendonly yes
    appendfsync everysec
    
    # Save settings (reduced frequency for resource conservation)
    save 900 1
    save 300 10
    
    # Disable RDB snapshots to save resources
    save ""
    
    # Security settings
    protected-mode yes
    
    # Performance tuning
    tcp-keepalive 300
    
    # Disable features not needed in a feature store context
    lazyfree-lazy-eviction yes
    lazyfree-lazy-expire yes
    
    # Logging
    loglevel notice
    
    # Network settings
    timeout 0
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: storage
type: Opaque
stringData:
  redis-password: mlops-redis-password
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: storage
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6.2-alpine
        command:
          - redis-server
          - "/redis-config/redis.conf"
          - "--requirepass"
          - "$(REDIS_PASSWORD)"
        ports:
        - containerPort: 6379
          name: redis
        resources:
          requests:
            cpu: "50m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
        volumeMounts:
        - name: redis-config
          mountPath: /redis-config
        - name: redis-data
          mountPath: /data
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redis-password
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - redis-cli -a $REDIS_PASSWORD ping | grep PONG
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - redis-cli -a $REDIS_PASSWORD ping | grep PONG
          initialDelaySeconds: 15
          periodSeconds: 15
      volumes:
      - name: redis-config
        configMap:
          name: redis-config
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-data
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: storage
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
    name: redis 